### ISSUE TITLE
Crash upon hovering button tooltip, moving cursor outside of window, then immediately back onto button

### ISSUE THREAD

**Issue by mcdcam** [kivymd/KivyMD#1220]
### Description of the Bug

When moving your cursor over ~~an MDTopAppBar~~ a button with a tooltip, and then out of the window, then back onto the button, there is a chance the app will crash, as the tooltip is attempted to be added to the window when it is already there, resulting in an error such as `kivy.uix.widget.WidgetException: Cannot add <kivymd.uix.tooltip.tooltip.MDTooltipViewClass object...> to window, it already has a parent <kivy.core.window.window_sdl2.WindowSDL object...>`. In normal use, this is quite rare, I probably experience it on average once per 15-20 minutes, however it can be intentionally triggered in under a few seconds.

~~I don't know why this issue is specific to MD(Top/Bottom)AppBars, but~~ the crash is happening in `tooltip.py`, on [line 204](https://github.com/kivymd/KivyMD/blob/13400aadd4a32fb58a930133d37265049d8c8578/kivymd/uix/tooltip/tooltip.py#L204), where the tooltip is added to the window (perhaps a check for whether it already has a parent is needed?).

#### EDIT:
After reducing the size of the other button, I was able to reproduce the error outside of an MDTopAppBar. It seems the bug affects all tooltips.

### Code and Logs
Minimal demo:

```python
from kivymd.app import MDApp
from kivy.lang import Builder

kv = """
<TooltipMDIconButton@MDIconButton+MDTooltip>

MDBoxLayout:
    orientation: "vertical"

    MDTopAppBar:
        # THE TOOLTIPS CAUSING THE ISSUE ARE DEFINED HERE
        title: "Title"
        left_action_items:[["arrow-left", app.callback, "Back"]]
        right_action_items: [["home", app.callback, "Home"], ["account", app.callback, "Account"]]

    MDFloatLayout:
        TooltipMDIconButton:
            icon: "language-python"
            icon_size: dp(24)
            tooltip_text: self.icon
            pos_hint: {"center_x": .06, "center_y": .08}
"""

class MainApp(MDApp):
    def callback(self, button):
        print('Callback')

    def build(self):
        self.root = Builder.load_string(kv)


if __name__ == '__main__':
    MainApp().run()
```

#### Steps to Reproduce:
- Run the above code
- Rapidly jiggle cursor over one of the ~~TopAppBar~~ buttons, moving it over the button, outside of the bounds of the window, then back over the button etc. (see video for demo)
- Continue until the app crashes (typically about 1-15 seconds)
- Repeat with the MDIconButton and ~~observe no crash~~ observe a crash as well

Logs:
```
Traceback (most recent call last):
   File "/Users/<user>/PycharmProjects/<project>/venv/lib/python3.9/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/Users/<user>/PycharmProjects/<project>/venv/lib/python3.9/site-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/Users/<user>/PycharmProjects/<project>/venv/lib/python3.9/site-packages/kivy/base.py", line 379, in idle
     Clock.tick()
   File "/Users/<user>/PycharmProjects/<project>/venv/lib/python3.9/site-packages/kivy/clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "/Users/<user>/PycharmProjects/<project>/venv/lib/python3.9/site-packages/kivy/clock.py", line 776, in post_idle
     self._process_events()
   File "kivy/_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "/Users/<user>/PycharmProjects/<project>/venv/lib/python3.9/site-packages/kivymd/uix/tooltip/tooltip.py", line 204, in display_tooltip
     Window.add_widget(self._tooltip)
   File "/Users/<user>/PycharmProjects/<project>/venv/lib/python3.9/site-packages/kivy/core/window/__init__.py", line 1487, in add_widget
     raise WidgetException(
 kivy.uix.widget.WidgetException: Cannot add <kivymd.uix.tooltip.tooltip.MDTooltipViewClass object at 0x7f996b7a1350> to window, it already has a parent <kivy.core.window.window_sdl2.WindowSDL object at 0x7f9968b84820>
```

### Screenshots/Videos

https://user-images.githubusercontent.com/59149640/161454668-4f92192e-5eab-4266-adeb-3e66498ea1fc.mov

### Versions

* OS: MacOS 10.15
* Python: 3.9.1
* Kivy: 2.1.0
* KivyMD: 1.0.0dev0 (latest commit dcf3520f6d75324dc604756ae383fc841b8bb1c3), also experienced on 0.104.2

**Comment by mcdcam** [comment]
After changing [line 202 of tooltip.py](https://github.com/kivymd/KivyMD/blob/13400aadd4a32fb58a930133d37265049d8c8578/kivymd/uix/tooltip/tooltip.py#L202) from `if not self._tooltip:` to `if not self._tooltip or self._tooltip.parent:` I cannot reproduce the issue, and the tooltips otherwise appear to function as normal.

**Comment by HeaTTheatR** [comment]
@very-lame-username Thanks for the analysis. I fixed it on your advice!

**Comment by mcdcam** [comment]
@HeaTTheatR Your change did not resolve the issue.

`if not self._tooltip and not self._tooltip.parent:` does not prevent the crash, as it will only return if there is no tooltip _and_ the tooltip does not have a parent (meaning if there is no tooltip, you will get another crash, as None has no parent), and if there is a tooltip but it already has a parent, both conditions will be false.

I think you misunderstood what I changed as `not (self._tooltip or self._tooltip.parent)` rather than `(not self._tooltip) or (self._tooltip.parent)`. Perhaps it would be better as 2 separate if statements for clarity.

**Comment by HeaTTheatR** [comment]
@very-lame-username OK. I will return to this issue in the evening...

**Comment by mcdcam** [comment]
@HeaTTheatR
