### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by biplobsd** [kivymd/KivyMD#365]
### Description of the Bug

On updated master brach. 
I used this c67850fd9f505d20a9e86ab89a39918daf34cd43 all work fine!. But later all, i not sure which commit later this's problem start!
I also check! workflow demo build https://github.com/HeaTTheatR/KivyMD/suites/831018154/artifacts/9277916 same issue.
### Screenshots
![Screenshot_20200624-005559](https://user-images.githubusercontent.com/43641536/85446836-c14dd400-b5b6-11ea-814a-6ec9b2b73d86.jpg)
### Versions
* OS: Android 10
* Python: 3.7.5
* Kivy: v2.0.0rc3, git-3ae5964, 20200623
* KivyMD: v0.104.1

**Comment by HeaTTheatR** [comment]
@biplobsd See this issue (maybe this will be useful) - https://github.com/HeaTTheatR/KivyMD/issues/257

**Comment by biplobsd** [comment]
@HeaTTheatR, Not fixed yet! Thanks for listed this's issue!
![image](https://user-images.githubusercontent.com/43641536/85695933-4c83b280-b6fa-11ea-9308-0480a62a38f6.png)

**Comment by HeaTTheatR** [comment]
@biplobsd This is fixed!

**Comment by HeaTTheatR** [comment]
@biplobsd When building a package for Android, you need to use the master version of the KivyMD library.

**Comment by biplobsd** [comment]
@HeaTTheatR I tested few minutes later your latest commit build domo apk Artifacts https://github.com/HeaTTheatR/KivyMD/suites/839974085/artifacts/9464569 . On my phone not fixed yet!

Also i changed my custom rom(derpfest) ! same!

**Comment by HeaTTheatR** [comment]
@biplobsd
Remove `.buildozer` and run `buildozer android debug` again.

**Comment by HeaTTheatR** [comment]
@biplobsd https://github.com/HeaTTheatR/KivyMD/blob/master/demos/kitchen_sink/buildozer.spec#L27

**Comment by biplobsd** [comment]
> @biplobsd When building a package for Android, you need to use the master version of the KivyMD library.

You mean this's `git+https://github.com/HeaTTheatR/KivyMD.git`

**Comment by HeaTTheatR** [comment]
@biplobsd When building a package for Android, you `need to use the master version` of the KivyMD library.

**Comment by ArtemSBulgakov** [comment]
Solution: https://github.com/HeaTTheatR/KivyMD/issues/257#issuecomment-665599554
