### ISSUE TITLE
hint_animation of MDFloatingActionButtonSpeedDial does not work

### ISSUE THREAD

**Issue by LivioAlvarenga** [kivymd/KivyMD#979]
### Description of the Bug
When activating the button's event (hint_animation: True) of (MDFloatingActionButtonSpeedDial) and starting the script when I click the button I have the error:

"
line 1819, in on_leave
     if self.data[instance.icon] == widget.text:
 KeyError: 'file-powerpoint-outline'
"
The error happens when I move the mouse off the button.

Thanks for the help.

### Code and Logs

```
from kivy.lang import Builder
from kivymd.app import MDApp
from rpa_kivy_code import menu_arquivo

class Rpa_App(MDApp):
    data_menu_arquivo = {'Novo Projeto': 'file-powerpoint-outline',
                        'Abrir Projeto': 'folder-open',
                        'Salvar': 'content-save',
                        'Salvar Como': 'content-save-move'}
    
    
    def callback(self, instance):
        print(instance.icon)

    def build(self):
        return Builder.load_string(menu_arquivo)

Rpa_App().run()

# KV code
# file: rpa_kivy_code.py

menu_arquivo = '''
MDScreen:

    MDFloatingActionButtonSpeedDial:
        callback: app.callback
        hint_animation: True
        data: app.data_menu_arquivo
        root_button_anim: True
        icon: 'alpha-m-circle-outline'

'''
```

### Screenshots
![Capturar2](https://user-images.githubusercontent.com/68560929/117384213-de328380-aeb8-11eb-99e1-a278e4aece2d.PNG)

![Capturar1](https://user-images.githubusercontent.com/68560929/117383724-d1616000-aeb7-11eb-9875-15b367da92f6.PNG)

![Capturar3](https://user-images.githubusercontent.com/68560929/117441448-c0423e80-af0b-11eb-9b6f-9908cc600400.PNG)

### Versions

* OS: Win 10 64
* Python:  3.8.5 64-bit (base:conda)
* Kivy: 2.0.0
* KivyMD: 0.104.2.dev0

**Comment by Guhan-SenSam** [comment]
Everything seems to be working without crashing for me. I removed the import `from rpa_kivy_code import menu_arquivo
` as I don't have that file and i moved the kv code definition to the beginning of the file just below the imports and everything works. Are you sure you are using the dev version from Github main branch?

**Comment by Guhan-SenSam** [comment]
https://github.com/kivymd/KivyMD/issues/954#issue-855148237 This also could be helpful

**Comment by hmae** [comment]
As mentioned in previous issue > https://github.com/kivymd/KivyMD/issues/954#issuecomment-817322906
---
it is solved after updating kivymd/uix/button.py file by this one >> [kivymd/uix/button.py](https://github.com/VICTORVICKIE/KivyMD/blob/286522247bfc081363a442acb66d7850b8da8dd8/kivymd/uix/button.py)
thanks for @VICTORVICKIE

**Comment by LivioAlvarenga** [comment]
@Guhan-SenSam  @hmae Thank you for your help. But it still doesn't work for me.

```
from kivy.lang import Builder
from kivymd.app import MDApp

KV = '''
MDScreen:

    MDFloatingActionButtonSpeedDial:
        data: app.data
        root_button_anim: True
        hint_animation: True
'''

class Example(MDApp):
    data = {
        'Python': 'language-python',
        'PHP': 'language-php',
        'C++': 'language-cpp',
    }

    def build(self):
        return Builder.load_string(KV)


Example().run()
```
See this code, it is the same as the one in the kivymd documentation. And a have the same error.

```
PS C:\Users\Avell\OneDrive\Cursos\Biblioteca_Conhecimento> & C:/Users/Avell/anaconda3/python.exe c:/Users/Avell/OneDrive/Cursos/Biblioteca_Conhecimento/_Programação_Biblioteca/Python/Kivy/teste.py
[INFO   ] [Logger      ] Record log in C:\Users\Avell\.kivy\logs\kivy_21-05-10_42.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.3.2
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "C:\Users\Avell\anaconda3\lib\site-packages\kivy\__init__.py"     
[INFO   ] [Python      ] v3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\Avell\anaconda3\python.exe"
[INFO   ] [KivyMD      ] 0.104.2.dev0, git-Unknown, 
2021-05-05 (installed at "C:\Users\Avell\anaconda3\lib\site-packages\kivymd\__init__.py")
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)        
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>        
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 461.56'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce 
RTX 2080 Super with Max-Q Design/PCIe/SSE2'>        
[INFO   ] [GL          ] OpenGL parsed version: 4, 6[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>   
[INFO   ] [GL          ] Texture max units <32>     
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "c:/Users/Avell/OneDrive/Cursos/Biblioteca_Conhecimento/_Programação_Biblioteca/Python/Kivy/teste.py", line 23, in <module>
     Example().run()
   File "C:\Users\Avell\anaconda3\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\Users\Avell\anaconda3\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "C:\Users\Avell\anaconda3\lib\site-packages\kivy\base.py", line 349, in mainloop
     self.window.mainloop()
   File "C:\Users\Avell\anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 524, in mainloop
     x, y = self._fix_mouse_pos(x, y)
   File "C:\Users\Avell\anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 473, in _fix_mouse_pos
     self.mouse_pos = (x * self._density,
   File "kivy\properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 545, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
   File "C:\Users\Avell\anaconda3\lib\site-packages\kivymd\uix\behaviors\hover_behavior.py", line 156, in on_mouse_update
     self.dispatch("on_leave")
   File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1172, in kivy._event.EventObservers._dispatch
   File "C:\Users\Avell\anaconda3\lib\site-packages\kivymd\uix\button.py", line 1819, in on_leave       
     if self.data[instance.icon] == widget.text:    
 KeyError: 'language-python'
PS C:\Users\Avell\OneDrive\Cursos\Biblioteca_Conhecimento>
```
I would be very grateful if you could help me. I would like to know if this problem is with my computer or if it is a bug in the hint_animation: True attribute.

Thanks again for your help.

**Comment by hmae** [comment]
it is a bug in kivymd .. exactly in this file > kivymd/uix/button.py
when i created an issue about it .. VICTORVICKIE answered with a solution .. but it didnt included in kivymd main branch yet .. so you cant fix it by using pip ..
in my case ,
i copied the code manually from his repository to my local kivymd .. just replace the code ( copy & past )
as a temporary solution .. 🤔

**Comment by VICTORVICKIE** [comment]
yes, can confirm this has already been addressed as @hmae said its fixed in my local repo. Try replacing using this [button.py](https://raw.githubusercontent.com/VICTORVICKIE/KivyMD/286522247bfc081363a442acb66d7850b8da8dd8/kivymd/uix/button.py)

**Comment by LivioAlvarenga** [comment]
Now It's working. Nice you're the best. Thank you so much. @VICTORVICKIE, @hmae and @Guhan-SenSam . I hope that I can  contribute someday as you do. Thanks.
